// Double hack. :-(
//
// We need a cmake target for the header files generated by soac, so that
// they can be added as a dependency to pbrt_lib, so that they're generated
// first. That's currently done via a add_library() that includes those
// headers. (Hack #1; I assume there's a better way...)
//
// In turn, the OSX tries to run "ar" on a library with nothing in it,
// which breaks the build. So, this is an empty .cpp file to put in that
// library.  (Hack #2.)
//
// I'm sure there's a better way...
